ALTER TABLE "Producto" ADD COLUMN IF NOT EXISTS "costoFijo" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "Producto" ADD COLUMN IF NOT EXISTS "comisionPorVenta" DECIMAL(65,30);
ALTER TABLE "Producto" ADD COLUMN IF NOT EXISTS "comisionPorcentaje" DECIMAL(65,30);
