ALTER TABLE "EnvioDespacho"
  ADD COLUMN IF NOT EXISTS "costoEnvio" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "pagarFlete" TEXT DEFAULT 'NEGOCIO',
  ADD COLUMN IF NOT EXISTS "aplicacionMontoCliente" TEXT DEFAULT 'NEGOCIO';
