-- AlterTable
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "costoEnvioFijo" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "envioGratisDesdeSoles" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "Empresa" ADD COLUMN IF NOT EXISTS "minimoCompra" DECIMAL(65,30) DEFAULT 0;
